-- Exercise library expansion · authored under Exercise Science Advisor review.
-- Same controlled vocabulary as 0002_seed_exercises.sql (movement patterns,
-- contraindication tags). Global rows (trainer_id NULL). Adds CrossFit,
-- functional movement, Hyrox, HIIT, yoga, mat Pilates, and senior-specific
-- exercises.

insert into exercises
  (name, description, pattern, muscle_groups, equipment_types, difficulty, cues, contraindication_tags, unilateral)
values

-- CROSSFIT ────────────────────────────────────────────────────────────
('Thruster', 'Front squat driven directly into an overhead press in one motion.', 'squat', '{quads,glutes,shoulders}', '{barbell}', 'advanced', E'Elbows high in the front rack\nStand up and press in one fluid motion\nFull lockout overhead', '{overhead,deep_knee_flexion,front_rack}', false),
('Wall Ball', 'Squat to a throw, catching the medicine ball and repeating.', 'squat', '{quads,glutes,shoulders}', '{medicine_ball}', 'intermediate', E'Squat below parallel\nDrive up and extend through the throw\nCatch soft, absorb into the next squat', '{deep_knee_flexion}', false),
('Kettlebell Snatch', 'Explosive one-arm pull from the floor to an overhead lockout.', 'conditioning', '{glutes,hamstrings,shoulders}', '{kettlebell}', 'advanced', E'Hike pass, then explosive hip snap\nPunch through at the top\nSoft-catch on the way down', '{overhead}', true),
('Box Jump', 'Explosive two-foot jump onto a box.', 'conditioning', '{quads,glutes}', '{box}', 'intermediate', E'Full hip extension at the top\nStep down, don''t jump down\nReset between reps if fatigued', '{high_impact,knee_dominant_plyo,deep_knee_flexion}', false),
('Double Unders', 'Jump rope passing under the feet twice per jump.', 'conditioning', '{calves,shoulders}', '{jump_rope}', 'intermediate', E'Small hop, wrists do the work\nStay tall, quiet landing', '{high_impact}', false),
('Toes-to-Bar', 'Hanging from a bar, raise the feet to touch it.', 'core_flexion', '{core,hip_flexors}', '{pullup_bar}', 'advanced', E'Initiate from a hollow hang\nControl the descent, no wild swinging', '{loaded_flexion,high_grip_demand,overhead}', false),
('Pistol Squat', 'Single-leg squat to full depth with the other leg extended forward.', 'squat', '{quads,glutes}', '{bodyweight}', 'advanced', E'Reach arms forward for balance\nSit back into the working hip\nControl through the bottom', '{deep_knee_flexion,single_leg_unstable}', true),
('Devil Press', 'Burpee combined with a two-dumbbell snatch to overhead.', 'conditioning', '{full_body}', '{dumbbell}', 'advanced', E'Chest to floor on the burpee\nHike the bells back, snatch to lockout\nPace this one — it adds up fast', '{high_impact,overhead,wrist_extension_load}', false),

-- FUNCTIONAL MOVEMENT ────────────────────────────────────────────────
('Turkish Get-Up', 'Floor-to-standing sequence keeping a weight locked out overhead throughout.', 'core_antirotation', '{core,shoulders}', '{kettlebell}', 'advanced', E'Eyes on the bell the whole way up\nMove slow, own each position\nReverse the pattern with the same control going down', '{overhead,supine_extended,loaded_rotation}', true),
('Suitcase Deadlift', 'One-sided deadlift with the load at the side rather than centered.', 'hinge', '{glutes,hamstrings,core}', '{kettlebell}', 'intermediate', E'Resist leaning toward the load\nHips and shoulders stay square\nStand tall at the top', '{heavy_spinal_load}', true),
('Bear Crawl', 'Crawl forward on hands and feet with knees hovering off the floor.', 'conditioning', '{core,shoulders}', '{bodyweight}', 'intermediate', E'Knees stay low, don''t rise up\nOpposite hand and foot move together\nFlat back throughout', '{wrist_extension_load,prone}', false),
('Medicine Ball Rotational Throw', 'Rotate through the trunk to throw a medicine ball against a wall.', 'core_antirotation', '{core,obliques}', '{medicine_ball}', 'intermediate', E'Rotate from the hips, not just the arms\nFull extension into the throw\nCatch and immediately load the next rep', '{loaded_rotation}', true),
('Single-Leg Romanian Deadlift', 'Hip hinge balanced on one leg, the other extending behind.', 'hinge', '{hamstrings,glutes}', '{dumbbell}', 'intermediate', E'Hips square to the floor\nReach the free leg back as you hinge\nLight touch of the working knee is fine', '{single_leg_unstable}', true),
('Lateral Lunge', 'Step wide to one side and sit back into that hip.', 'lunge', '{quads,glutes,adductors}', '{bodyweight}', 'beginner', E'Push hips back like sitting in a chair\nKeep the straight leg''s foot flat\nDrive back to center', '{deep_knee_flexion}', true),
('Renegade Row', 'Alternating dumbbell rows held in a plank position.', 'pull_horizontal', '{back,core}', '{dumbbell}', 'advanced', E'Minimize hip rotation as you row\nWide stance for a stable base\nRow to the hip pocket', '{wrist_extension_load}', true),
('Battle Ropes', 'Alternating or double-arm waves with heavy rope.', 'conditioning', '{shoulders,core}', '{battle_ropes}', 'intermediate', E'Athletic stance, knees soft\nWaves come from the shoulders, not just wrists\nKeep breathing rhythmic', '{}', false),

-- HYROX ──────────────────────────────────────────────────────────────
('Sled Push (Loaded)', 'Drive a weighted sled forward across a set distance.', 'conditioning', '{quads,glutes,core}', '{sled}', 'intermediate', E'Low shin angle, drive through the whole foot\nShort powerful steps\nExhale forcefully each push', '{}', false),
('Sled Pull', 'Pull a weighted sled backward or hand-over-hand using a rope.', 'conditioning', '{back,hamstrings,core}', '{sled}', 'intermediate', E'Sit into a low athletic stance\nDrive through the legs, not just the arms\nControl the sled, don''t let it run away', '{}', false),
('Ski Erg Intervals', 'Repeated pulling motion on a ski ergometer for set distance or time.', 'conditioning', '{back,core,triceps}', '{ski_erg}', 'beginner', E'Hinge from the hips, not just the arms\nFull extension at the top of each pull\nSteady rhythm over sprinting early', '{}', false),
('Rowing Erg Intervals', 'Repeated rowing strokes on an ergometer for set distance or time.', 'conditioning', '{back,hamstrings,core}', '{rower}', 'beginner', E'Legs, then hips, then arms on the drive\nReverse the order on the way back\nDon''t rush the recovery', '{}', false),
('Sandbag Carry', 'Carry a loaded sandbag against the chest or on a shoulder over distance.', 'carry', '{core,traps,grip}', '{sandbag}', 'intermediate', E'Brace hard before picking it up\nShort controlled steps\nSwitch shoulders evenly if carrying on one side', '{high_grip_demand}', true),
('Sandbag Lunge', 'Walking or stationary lunge carrying a sandbag at the chest or shoulder.', 'lunge', '{quads,glutes}', '{sandbag}', 'intermediate', E'Torso stays tall despite the offset load\nControl the descent each step\nDrive through the front heel', '{deep_knee_flexion}', true),
('Burpee Broad Jump', 'A burpee immediately followed by a maximal forward jump.', 'conditioning', '{full_body}', '{bodyweight}', 'advanced', E'Full chest-to-floor burpee\nStick the landing before your next rep\nReset your stance between jumps', '{high_impact,wrist_extension_load,deep_knee_flexion}', false),

-- HIIT ───────────────────────────────────────────────────────────────
('High Knees', 'Fast alternating knee drives toward the chest in place.', 'conditioning', '{hip_flexors,quads}', '{bodyweight}', 'beginner', E'Drive knees up, not just fast feet\nStay light on the balls of the feet\nPump the arms in rhythm', '{high_impact}', false),
('Skater Jumps', 'Lateral bounding from one leg to the other.', 'conditioning', '{quads,glutes,adductors}', '{bodyweight}', 'intermediate', E'Land soft on the outside leg\nReach the trailing leg behind for balance\nControl the landing before the next bound', '{high_impact,single_leg_unstable,cutting}', true),
('Plank Jacks', 'From a plank, jump the feet wide and back together.', 'core_antiextension', '{core,shoulders}', '{bodyweight}', 'beginner', E'Hips stay level the whole time\nQuiet, controlled landings\nDon''t let the hips pike up', '{wrist_extension_load}', false),
('Tuck Jump', 'Vertical jump driving both knees up toward the chest.', 'conditioning', '{quads,glutes,core}', '{bodyweight}', 'advanced', E'Land soft with bent knees\nReset fully between reps early on\nQuality over max height', '{high_impact,deep_knee_flexion,knee_dominant_plyo}', false),
('Squat Thrust', 'Step or jump back to a plank and immediately return to standing, no push-up.', 'conditioning', '{full_body}', '{bodyweight}', 'beginner', E'Step back if jumping feels like too much impact\nFlat back in the plank position\nStand fully tall each rep', '{high_impact,wrist_extension_load}', false),

-- YOGA ───────────────────────────────────────────────────────────────
('Downward Dog', 'Inverted V position with hands and feet on the floor.', 'mobility', '{shoulders,hamstrings,calves}', '{yoga_mat}', 'beginner', E'Press the floor away, lengthen the spine\nBend the knees if the hamstrings are tight\nHead relaxed between the arms', '{wrist_extension_load}', false),
('Child''s Pose', 'Kneeling forward fold with arms extended or relaxed at the sides.', 'mobility', '{hips,back}', '{yoga_mat}', 'beginner', E'Sit hips back toward the heels\nLet the forehead rest down\nBreathe into the low back', '{deep_knee_flexion}', false),
('Warrior II', 'Wide split stance with arms extended, front knee bent.', 'lunge', '{quads,glutes,shoulders}', '{yoga_mat}', 'beginner', E'Front knee tracks over the ankle\nBack foot grounded flat\nReach equally through both arms', '{}', true),
('Chair Pose', 'Standing isometric squat with arms raised overhead.', 'squat', '{quads,glutes,shoulders}', '{yoga_mat}', 'beginner', E'Weight in the heels\nTailbone tucks slightly under\nArms reach up without shrugging', '{}', false),
('Cat-Cow', 'Alternating spinal flexion and extension on hands and knees.', 'mobility', '{back,core}', '{yoga_mat}', 'beginner', E'Move slow, one vertebra at a time\nInhale to arch, exhale to round\nKeep the movement gentle, not forced', '{}', false),
('Cobra Pose', 'Gentle prone backbend supported by the hands.', 'mobility', '{back,chest}', '{yoga_mat}', 'beginner', E'Elbows stay soft, not locked\nLift from the chest, not by cranking the neck\nOnly go as high as feels easy', '{prone}', false),
('Pigeon Pose', 'Seated hip opener with one leg bent in front, one extended behind.', 'mobility', '{hips,glutes}', '{yoga_mat}', 'intermediate', E'Square the hips forward as much as comfortable\nUse a block or cushion under the hip if needed\nBreathe, don''t force depth', '{deep_hip_flexion}', true),
('Triangle Pose', 'Standing wide-legged pose with a lateral reach toward the front foot.', 'mobility', '{hamstrings,obliques}', '{yoga_mat}', 'beginner', E'Hinge from the hip, not the waist\nStack shoulders vertically\nLong spine, avoid collapsing forward', '{}', true),

-- MAT PILATES ────────────────────────────────────────────────────────
('The Hundred', 'Pulsing the arms while holding a curled-up core position, breathing in a five-count rhythm.', 'core_flexion', '{core}', '{yoga_mat}', 'intermediate', E'Low back stays pressed toward the mat\nLegs at whatever height keeps the low back down\nSmall, controlled arm pulses', '{loaded_flexion,supine_extended}', false),
('Pilates Roll-Up', 'Slow controlled roll from lying flat up to a seated forward fold.', 'core_flexion', '{core}', '{yoga_mat}', 'intermediate', E'Peel up one vertebra at a time\nReach forward over the legs at the top\nRoll down with the same control', '{loaded_flexion,supine_extended}', false),
('Single-Leg Stretch', 'Alternating knee-to-chest pulls while the opposite leg extends, upper body curled.', 'core_flexion', '{core,hip_flexors}', '{yoga_mat}', 'intermediate', E'Shoulders stay lifted off the mat\nSwitch legs with control, not momentum\nExhale on each switch', '{loaded_flexion,supine_extended}', true),
('Pilates Plank', 'Static forearm or full plank emphasizing scapular and core control.', 'core_antiextension', '{core,shoulders}', '{yoga_mat}', 'beginner', E'Long line from head to heels\nRibs knit down, no sagging\nSteady breathing throughout', '{wrist_extension_load}', false),
('Pilates Swimming', 'Prone alternating arm and leg lifts in a fluid, continuous rhythm.', 'core_antiextension', '{back,glutes}', '{yoga_mat}', 'intermediate', E'Lengthen through the crown of the head\nSmall controlled lifts, not big kicks\nKeep breathing throughout the flutter', '{prone}', false),
('Side-Lying Leg Series', 'Small controlled leg lifts and circles lying on one side.', 'core_antirotation', '{glutes,obliques}', '{yoga_mat}', 'beginner', E'Stay stacked — hips don''t roll forward or back\nMove from the hip, not momentum\nSmall range, high control', '{}', true),
('Spine Stretch Forward', 'Seated forward fold reaching over extended legs with a rounded spine.', 'mobility', '{hamstrings,back}', '{yoga_mat}', 'beginner', E'Round through the spine like curling over a beach ball\nReach long, don''t force the stretch\nCome up with control', '{loaded_flexion}', false),
('Pilates Shoulder Bridge', 'Supine bridge with a focus on articulating through the spine.', 'hinge', '{glutes,hamstrings}', '{yoga_mat}', 'beginner', E'Peel the spine off the mat one bone at a time\nSqueeze at the top\nLower with the same control', '{supine_extended}', false),

-- SENIOR-SPECIFIC ────────────────────────────────────────────────────
('Sit-to-Stand', 'Standing up from a chair and sitting back down with control.', 'squat', '{quads,glutes}', '{bodyweight}', 'beginner', E'Lean slightly forward before standing\nPush through the whole foot\nLower with control, don''t just drop', '{}', false),
('Wall Push-Up', 'Push-up performed standing against a wall for a gentler load.', 'push_horizontal', '{chest,triceps}', '{bodyweight}', 'beginner', E'Hands just wider than shoulders\nKeep the body in one line\nElbows point back, not flared', '{}', false),
('Seated Band Row', 'Rowing motion against a band while seated, supporting balance.', 'pull_horizontal', '{back,biceps}', '{band}', 'beginner', E'Sit tall, chest up\nSqueeze the shoulder blades together\nSlow release each rep', '{}', false),
('Heel-to-Toe Walk', 'Walking in a straight line placing the heel directly in front of the other foot.', 'mobility', '{calves,core}', '{bodyweight}', 'beginner', E'Use a wall or counter for light support if needed\nEyes forward, not down at the feet\nSmall, controlled steps', '{single_leg_unstable}', false),
('Standing March', 'Marching in place lifting the knees to a comfortable height.', 'conditioning', '{hip_flexors,quads}', '{bodyweight}', 'beginner', E'Hold onto a counter or chair if balance is a concern\nLift to a height that feels controlled\nSteady, comfortable pace', '{}', false),
('Seated Leg Extension', 'Extending one knee straight while seated to build quad strength.', 'mobility', '{quads}', '{bodyweight}', 'beginner', E'Sit tall, don''t lean back to compensate\nStraighten fully but without locking hard\nLower with control', '{}', true),
('Standing Balance Reach', 'Single-leg standing balance while reaching the opposite arm forward.', 'mobility', '{core,glutes}', '{bodyweight}', 'beginner', E'Keep a chair nearby for light support\nReach slowly, don''t rush the balance\nSwitch sides evenly', '{single_leg_unstable}', true),
('Seated Chest Press (Band)', 'Pressing motion against a band anchored behind, performed seated.', 'push_horizontal', '{chest,triceps}', '{band}', 'beginner', E'Sit tall against a chair back\nPress forward without shrugging the shoulders\nControl the return', '{}', false);
