-- Exercise batch cross-referenced against a submitted 136-item list to
-- eliminate duplicates (e.g. "Bulgarian Split Squat" = existing
-- "Rear-Foot-Elevated Split Squat"; "Squat Jump" = existing "Jump Squat";
-- "Cable Chop" = existing "Cable Woodchop"; etc.). These 98 are genuinely
-- new. Written originally under Exercise Science Advisor review, same
-- tagging vocabulary as every prior batch — no new contraindication tags
-- introduced. category column included directly (exists since 0004).

insert into exercises
  (name, description, pattern, category, muscle_groups, equipment_types, difficulty, cues, contraindication_tags, unilateral)
values

-- SQUAT / LUNGE FAMILY ───────────────────────────────────────────────
('Prisoner Squat', 'Bodyweight squat with hands held behind the head.', 'squat', 'Foundational strength', '{quads,glutes}', '{bodyweight}', 'beginner', E'Elbows wide, chest tall\nSit back into the squat\nDon''t let the elbows drift forward', '{deep_knee_flexion}', false),
('Dumbbell Front Squat', 'Squat holding two dumbbells at shoulder height.', 'squat', 'Foundational strength', '{quads,glutes,core}', '{dumbbell}', 'intermediate', E'Elbows up, dumbbells stay at the shoulders\nBrace before descending\nDrive through the whole foot', '{deep_knee_flexion,front_rack}', false),
('Kettlebell Front Squat', 'Squat holding two kettlebells racked at the shoulders.', 'squat', 'Foundational strength', '{quads,glutes,core}', '{kettlebell}', 'intermediate', E'Bells rest on the shoulders, elbows down and in\nBrace hard before descending\nStand tall at the top', '{deep_knee_flexion,front_rack}', false),
('Single-Leg Squat Touchdown', 'Single-leg squat lightly touching one hand to the floor.', 'squat', 'Functional movement', '{quads,glutes}', '{bodyweight}', 'intermediate', E'Reach with control, don''t rush the touch\nKnee tracks over the toes\nStand tall each rep', '{deep_knee_flexion,single_leg_unstable}', true),
('Single-Leg Squat to Row', 'Single-leg squat combined with a banded row at the bottom.', 'squat', 'Functional movement', '{quads,glutes,back}', '{band}', 'advanced', E'Squat first, row second — don''t rush either\nKeep the standing knee stable\nControl the band back', '{deep_knee_flexion,single_leg_unstable}', true),
('Lunge Jump', 'Explosive alternating jump switching legs in a lunge position.', 'lunge', 'HIIT', '{quads,glutes}', '{bodyweight}', 'advanced', E'Land soft in the lunge position\nDrive up, switch legs in the air\nReset pace if landings get sloppy', '{high_impact,knee_dominant_plyo,deep_knee_flexion}', false),
('Jumping Jacks', 'Classic full-body jumping movement, arms and legs out and in.', 'conditioning', 'HIIT', '{calves,shoulders}', '{bodyweight}', 'beginner', E'Land soft on the balls of the feet\nFull arm range overhead\nSteady rhythm', '{high_impact}', false),
('Single-Leg Press', 'Leg press performed one leg at a time.', 'squat', 'Foundational strength', '{quads,glutes}', '{full_gym}', 'intermediate', E'Full foot on the platform\nControl the negative\nDon''t let the knee cave in', '{single_leg_unstable}', true),
('Leg Press Calf Raise', 'Calf raise performed at the top of a leg press machine.', 'mobility', 'Foundational strength', '{calves}', '{full_gym}', 'beginner', E'Full range each rep\nPause at the top\nControl the stretch at the bottom', '{}', false),
('Single-Leg Balance Reach: Frontal Plane', 'Single-leg balance reaching the free leg out to the side.', 'mobility', 'Functional movement', '{glutes,core}', '{bodyweight}', 'intermediate', E'Stand tall on the working leg\nReach sideways with control\nStay light on the standing foot', '{single_leg_unstable}', true),

-- DEADLIFT / POSTERIOR ───────────────────────────────────────────────
('Romanian Deadlift (Barbell)', 'Barbell hip hinge lowering the bar along the legs.', 'hinge', 'Foundational strength', '{hamstrings,glutes,back}', '{barbell}', 'intermediate', E'Push hips back, soft knees\nBar stays close to the legs\nFeel the hamstrings, don''t round the back', '{heavy_spinal_load}', false),
('Good Mornings', 'Barbell hip hinge with the bar racked across the upper back.', 'hinge', 'Foundational strength', '{hamstrings,glutes,back}', '{barbell}', 'advanced', E'Soft knees, hinge from the hips\nFlat back throughout\nLight weight — this one is easy to overload', '{heavy_spinal_load}', false),

-- HAMSTRING ISOLATION ────────────────────────────────────────────────
('Lying Leg Curl: Single-Leg', 'Prone machine leg curl performed one leg at a time.', 'hinge', 'Foundational strength', '{hamstrings}', '{full_gym}', 'intermediate', E'Hips stay flat on the pad\nControl the return\nDon''t let the hips rise up', '{single_leg_unstable}', true),
('Lying Leg Curl: Two-Leg Concentric, Single-Leg Eccentric', 'Curl up with both legs, lower with one for extra hamstring load.', 'hinge', 'Foundational strength', '{hamstrings}', '{full_gym}', 'advanced', E'Curl up with both legs together\nLower slowly on one leg only\nAlternate which leg lowers each rep', '{single_leg_unstable}', true),
('Seated Leg Curl', 'Seated machine hamstring curl.', 'hinge', 'Foundational strength', '{hamstrings}', '{full_gym}', 'beginner', E'Back flat against the pad\nFull range without yanking\nControl the release', '{}', false),
('Single-Leg Seated Leg Curl', 'Seated machine hamstring curl performed one leg at a time.', 'hinge', 'Foundational strength', '{hamstrings}', '{full_gym}', 'intermediate', E'Same setup as the two-leg version\nControl each rep independently\nKeep the hips square', '{}', true),

-- CHEST / PUSH ───────────────────────────────────────────────────────
('Modified Push-Up', 'Push-up performed from the knees.', 'push_horizontal', 'Foundational strength', '{chest,triceps,shoulders}', '{bodyweight}', 'beginner', E'Straight line from knees to head\nElbows ~45 degrees\nFull range each rep', '{wrist_extension_load}', false),
('Decline Push-Up', 'Push-up with the feet elevated for extra upper-chest emphasis.', 'push_horizontal', 'Foundational strength', '{chest,shoulders,triceps}', '{bodyweight,box}', 'intermediate', E'Feet on a stable surface\nSame plank standards as a standard push-up\nHigher feet = harder', '{wrist_extension_load}', false),
('Archer Push-Up', 'Push-up shifting weight to one arm while the other stays extended.', 'push_horizontal', 'Foundational strength', '{chest,triceps,shoulders}', '{bodyweight}', 'advanced', E'Wide hand placement\nShift the weight, don''t just lean\nAlternate sides each rep', '{wrist_extension_load}', true),
('Plyometric Push-Up', 'Explosive push-up with the hands leaving the floor.', 'push_horizontal', 'HIIT', '{chest,triceps,shoulders}', '{bodyweight}', 'advanced', E'Push explosively, land soft\nKeep the plank line tight\nScale to a smaller hop if needed', '{wrist_extension_load,high_impact}', false),
('Barbell Bench Press', 'Classic flat barbell press.', 'push_horizontal', 'Foundational strength', '{chest,triceps,shoulders}', '{barbell,bench}', 'intermediate', E'Feet planted, slight arch\nBar to mid-chest, press to lockout\nUse a spotter for heavier loads', '{}', false),
('Incline Barbell Bench Press', 'Barbell press on an inclined bench for upper-chest emphasis.', 'push_horizontal', 'Foundational strength', '{chest,shoulders,triceps}', '{barbell,bench}', 'intermediate', E'30-45 degree incline\nBar to the upper chest\nControl the descent', '{}', false),
('Barbell Bench Press with Bands', 'Bench press with resistance bands adding accommodating resistance.', 'push_horizontal', 'Foundational strength', '{chest,triceps,shoulders}', '{barbell,bench,band}', 'advanced', E'Bands anchored securely below\nExpect the press to get harder near lockout\nControl the descent against the band tension', '{}', false),
('Barbell Bench Press with Chains', 'Bench press with chains adding accommodating resistance as the bar rises.', 'push_horizontal', 'Foundational strength', '{chest,triceps,shoulders}', '{barbell,bench}', 'advanced', E'Chains should deload near the bottom\nExpect the press to get harder near lockout\nControl the descent as chain links stack', '{}', false),
('Chest Press Machine', 'Seated horizontal press machine for the chest.', 'push_horizontal', 'Foundational strength', '{chest,triceps,shoulders}', '{full_gym}', 'beginner', E'Adjust the seat so handles align with mid-chest\nFull range, controlled tempo\nDon''t lock the elbows out hard', '{}', false),
('Single-Arm Dumbbell Chest Press', 'Bench press performed one arm at a time for added core demand.', 'push_horizontal', 'Foundational strength', '{chest,triceps,core}', '{dumbbell,bench}', 'advanced', E'Resist rotating toward the working side\nBrace the core throughout\nControl the negative', '{}', true),
('Single-Arm Incline Dumbbell Chest Press', 'Incline bench press performed one arm at a time.', 'push_horizontal', 'Foundational strength', '{chest,shoulders,core}', '{dumbbell,bench}', 'advanced', E'Resist rotating toward the working side\nBrace hard\nControl the descent', '{}', true),
('Two-Arm Dumbbell Chest Press with Band', 'Dumbbell bench press with a band adding accommodating resistance.', 'push_horizontal', 'Foundational strength', '{chest,triceps,shoulders}', '{dumbbell,bench,band}', 'intermediate', E'Band anchored securely under the bench\nExpect more resistance near lockout\nControl the negative', '{}', false),
('Cable Crossover', 'Standing cable fly bringing the hands together in front of the chest.', 'push_horizontal', 'Foundational strength', '{chest}', '{cable_machine}', 'intermediate', E'Slight forward lean, soft elbows\nSqueeze the chest at the finish\nControl the stretch back', '{}', false),
('Two-Arm Standing Cable Fly', 'Standing cable fly at chest height, both arms together.', 'push_horizontal', 'Foundational strength', '{chest}', '{cable_machine}', 'beginner', E'Split stance for stability\nSoft elbows, lead with the hands\nControl the return', '{}', false),
('Close-Grip Bench Press', 'Bench press with a narrow grip, shifting emphasis to the triceps.', 'push_horizontal', 'Foundational strength', '{triceps,chest}', '{barbell,bench}', 'intermediate', E'Hands just inside shoulder width\nElbows track close to the body\nControl the bar to the chest', '{}', false),
('Bench Dips', 'Tricep dips using a bench behind you.', 'push_horizontal', 'Foundational strength', '{triceps,chest}', '{bench}', 'intermediate', E'Elbows track straight back\nDon''t sink deeper than a comfortable range\nKeep shoulders down away from the ears', '{wrist_extension_load,dip}', false),

-- SHOULDER PUSH ──────────────────────────────────────────────────────
('Inverted Push-Up', 'Push-up with the feet elevated well above the hands for shoulder emphasis.', 'push_vertical', 'Foundational strength', '{shoulders,triceps}', '{bodyweight,box}', 'advanced', E'Higher feet = more shoulder emphasis\nHead stays between the arms\nBuild up from a moderate elevation first', '{overhead,wrist_extension_load}', false),

-- BACK / PULL ────────────────────────────────────────────────────────
('Seated Machine Row: Close Grip', 'Seated cable/machine row using a close, neutral grip.', 'pull_horizontal', 'Foundational strength', '{back,biceps}', '{full_gym}', 'beginner', E'Chest up, don''t round forward to reach\nPull to the lower ribs\nSqueeze the shoulder blades together', '{}', false),
('Floor Prone Cobra', 'Prone back-extension activation exercise lifting the chest and arms.', 'pull_horizontal', 'Foundational strength', '{back,shoulders}', '{bodyweight}', 'beginner', E'Thumbs point up as you lift\nSmall controlled range\nSqueeze the shoulder blades together', '{prone}', false),

-- ARMS ───────────────────────────────────────────────────────────────
('Kettlebell Crush Curl with Squat', 'Bicep curl squeezing a kettlebell combined with a squat.', 'squat', 'Functional movement', '{biceps,quads,glutes}', '{kettlebell}', 'intermediate', E'Squeeze the bell hard throughout\nSquat and curl together\nStand tall at the top', '{deep_knee_flexion}', false),

-- CORE ───────────────────────────────────────────────────────────────
('Straight-Arm Plank', 'Plank held on extended arms rather than forearms.', 'core_antiextension', 'Foundational strength', '{core,shoulders}', '{bodyweight}', 'beginner', E'Hands under the shoulders\nLong line from head to heels\nDon''t let the hips sag or pike', '{wrist_extension_load}', false),
('Plank Walkup', 'Transitioning from a forearm plank to a straight-arm plank and back.', 'core_antiextension', 'Foundational strength', '{core,shoulders}', '{bodyweight}', 'intermediate', E'One arm at a time, minimize hip rocking\nKeep the core braced throughout\nAlternate the leading arm', '{wrist_extension_load}', false),
('Russian Twist', 'Seated rotational core exercise, feet lifted or grounded.', 'core_antirotation', 'Foundational strength', '{core,obliques}', '{bodyweight}', 'beginner', E'Lean back to a stable angle\nRotate from the trunk, control the tempo\nKeep feet down if the lifted version is too much', '{loaded_rotation}', false),
('Reverse Crunch to Knee-Up with Rotation', 'Reverse crunch adding a rotational knee drive at the top.', 'core_flexion', 'Functional movement', '{core,obliques}', '{bodyweight}', 'intermediate', E'Curl the hips up and rotate the knees to one side\nControl the lowering\nAlternate sides', '{loaded_flexion,supine_extended,loaded_rotation}', true),
('Iron Cross', 'Lying rotational mobility drill sweeping the legs side to side.', 'mobility', 'Functional movement', '{core,hips}', '{bodyweight}', 'intermediate', E'Arms out wide for stability\nControl the leg sweep, don''t let it slam down\nKeep shoulders on the floor', '{supine_extended,loaded_rotation}', false),

-- FOAM ROLLING ───────────────────────────────────────────────────────
('Foam Roll: Adductors', 'Self-myofascial release for the inner thigh using a foam roller.', 'mobility', 'Foundational strength', '{adductors}', '{foam_roller}', 'beginner', E'Prop up on the forearms, roller under the inner thigh\nSlow, controlled passes\nPause on tender spots, don''t rush through', '{}', false),
('Foam Roll: Calves', 'Self-myofascial release for the calves using a foam roller.', 'mobility', 'Foundational strength', '{calves}', '{foam_roller}', 'beginner', E'Sit with the roller under the calf\nSlow passes from ankle to knee\nCross one leg over to add pressure if needed', '{}', false),
('Foam Roll: Latissimus Dorsi', 'Self-myofascial release for the lats using a foam roller.', 'mobility', 'Foundational strength', '{back}', '{foam_roller}', 'beginner', E'Lie on your side, roller under the armpit/lat area\nSlow passes, arm extended overhead\nPause on tender spots', '{}', false),

-- STATIC STRETCHES ───────────────────────────────────────────────────
('Static: Butterfly Stretch', 'Seated inner-thigh stretch with the soles of the feet together.', 'mobility', 'Foundational strength', '{adductors,hips}', '{bodyweight}', 'beginner', E'Sit tall, don''t round the back\nGently press the knees toward the floor\nHold, breathe, don''t bounce', '{}', false),
('Static: Latissimus Dorsi Ball Stretch', 'Lat stretch using a stability ball to deepen the reach.', 'mobility', 'Foundational strength', '{back}', '{stability_ball}', 'beginner', E'Kneel with hands on the ball, roll it forward\nSink the chest toward the floor\nHold and breathe', '{}', false),
('Static: Seated Calf Stretch', 'Seated calf stretch using a strap, towel, or band.', 'mobility', 'Foundational strength', '{calves}', '{band}', 'beginner', E'Leg extended, loop around the foot\nGently pull the toes toward you\nHold without bouncing', '{}', false),
('Static: Standing Adductor Stretch', 'Standing wide-stance side stretch targeting the inner thigh.', 'mobility', 'Foundational strength', '{adductors}', '{bodyweight}', 'beginner', E'Wide stance, shift weight to one side\nKeep the straight leg''s foot flat\nHold, then switch sides', '{}', true),

-- CORE / BALL / CABLE ────────────────────────────────────────────────
('Ball Crunch', 'Crunch performed on a stability ball for extra range of motion.', 'core_flexion', 'Functional movement', '{core}', '{stability_ball}', 'beginner', E'Lower back stays supported by the ball\nCurl up through the chest, not the neck\nControl the lowering', '{loaded_flexion}', false),
('Ball Crunch with Rotation', 'Stability ball crunch adding a rotational twist at the top.', 'core_flexion', 'Functional movement', '{core,obliques}', '{stability_ball}', 'intermediate', E'Curl and rotate toward one shoulder\nControl the lowering\nAlternate sides', '{loaded_flexion,loaded_rotation}', true),
('Cable Rotation', 'Standing rotational cable pull at a fixed height.', 'core_antirotation', 'Functional movement', '{core,obliques}', '{cable_machine}', 'intermediate', E'Rotate from the trunk, arms stay relatively fixed\nControl the return, don''t let it whip\nPivot the back foot naturally', '{loaded_rotation}', true),
('Cable Lift', 'Diagonal cable pull from low to high across the body.', 'core_antirotation', 'Functional movement', '{core,shoulders}', '{cable_machine}', 'intermediate', E'Rotate and lift together, driven from the hips and trunk\nControl the return\nPivot the back foot naturally', '{loaded_rotation}', true),
('Reverse Crunch', 'Lying core exercise curling the hips and knees toward the chest.', 'core_flexion', 'Foundational strength', '{core}', '{bodyweight}', 'beginner', E'Curl the hips off the floor, not just the knees\nControl the lowering\nAvoid using momentum to swing the legs', '{loaded_flexion,supine_extended}', false),
('Back Extension', 'Posterior-chain extension performed on a hyperextension bench.', 'mobility', 'Foundational strength', '{back,glutes,hamstrings}', '{full_gym}', 'intermediate', E'Hinge from the hips, flat back\nDon''t hyperextend at the top — stop in line\nControl the descent', '{heavy_spinal_load}', false),

-- FUNCTIONAL COMBO / BALANCE SERIES ──────────────────────────────────
('Supine Marching', 'Lying core stability drill alternating gentle knee lifts.', 'core_antiextension', 'Functional movement', '{core}', '{bodyweight}', 'beginner', E'Low back stays gently pressed down\nSmall controlled knee lifts\nBreathe throughout', '{supine_extended}', false),
('Quadruped Arm Raise', 'Kneeling stability drill raising one arm at a time.', 'core_antirotation', 'Functional movement', '{core,shoulders}', '{bodyweight}', 'beginner', E'Hips and shoulders stay square\nReach long, don''t just lift\nAlternate arms', '{}', true),
('Marching Floor Bridge', 'Glute bridge hold with an alternating knee march.', 'hinge', 'Functional movement', '{glutes,core}', '{bodyweight}', 'intermediate', E'Hold the bridge height steady while marching\nDon''t let the hips dip on the lifted side\nControlled tempo', '{supine_extended}', false),
('Ball Bridge', 'Glute bridge with the feet elevated on a stability ball.', 'hinge', 'Functional movement', '{glutes,hamstrings,core}', '{stability_ball}', 'intermediate', E'Feet stable on the ball before lifting\nSqueeze at the top\nControl the ball throughout', '{supine_extended}', false),
('Ball Bridge with Leg Curl', 'Stability ball bridge adding a leg curl at the top.', 'hinge', 'Functional movement', '{hamstrings,glutes,core}', '{stability_ball}', 'advanced', E'Bridge up first, then curl the ball in\nKeep the hips level throughout\nControl every phase', '{supine_extended}', false),
('Ball Bridge with Hip Rotation', 'Stability ball bridge adding a controlled hip rotation.', 'hinge', 'Functional movement', '{glutes,core,obliques}', '{stability_ball}', 'advanced', E'Hold the bridge, then rotate the hips slowly\nKeep the ball stable\nControl the range, don''t force it', '{supine_extended,loaded_rotation}', false),
('Single-Leg Balance', 'Simple single-leg standing balance hold.', 'mobility', 'Functional movement', '{core,glutes}', '{bodyweight}', 'beginner', E'Soft knee on the standing leg\nStay tall through the spine\nUse a wall for light support if needed', '{single_leg_unstable}', true),
('Single-Leg Balance with Multiplanar Reach', 'Single-leg balance reaching the free leg in multiple directions.', 'mobility', 'Functional movement', '{core,glutes}', '{bodyweight}', 'advanced', E'Reach forward, side, and back with control\nStay light on the standing foot\nReset between directions if needed', '{single_leg_unstable}', true),
('Single-Leg Lift and Chop', 'Single-leg balance combined with a diagonal band chop.', 'core_antirotation', 'Functional movement', '{core,glutes}', '{band}', 'advanced', E'Balance first, then add the chop\nMove slow and controlled\nReset if balance breaks down', '{single_leg_unstable,loaded_rotation}', true),
('Single-Leg Lift and Chop with Medicine Ball', 'Single-leg balance combined with a diagonal medicine ball chop.', 'core_antirotation', 'Functional movement', '{core,glutes}', '{medicine_ball}', 'advanced', E'Balance first, then add the chop\nLight ball to start\nReset if balance breaks down', '{single_leg_unstable,loaded_rotation}', true),
('Single-Leg Romanian Deadlift to Row', 'Single-leg RDL combined with a dumbbell row at the bottom.', 'hinge', 'Functional movement', '{hamstrings,glutes,back}', '{dumbbell}', 'advanced', E'Hinge first, row second\nHips stay square throughout\nStand tall to finish each rep', '{single_leg_unstable}', true),
('Lunge to Balance', 'Reverse lunge stepping back to a single-leg balance hold.', 'lunge', 'Functional movement', '{quads,glutes,core}', '{bodyweight}', 'intermediate', E'Step back into the lunge, drive through the front heel\nPause in balance at the top\nReset before the next rep', '{single_leg_unstable,deep_knee_flexion}', true),
('Multiplanar Lunge to Balance', 'Lunge to balance varying the stepping direction (forward, lateral, rotational).', 'lunge', 'Functional movement', '{quads,glutes,core}', '{bodyweight}', 'advanced', E'Change the lunge direction each rep\nPause in balance before the next step\nQuality over speed', '{single_leg_unstable,deep_knee_flexion}', true),
('Step-Up to Balance', 'Step-up finishing in a single-leg balance hold at the top.', 'lunge', 'Functional movement', '{quads,glutes,core}', '{box}', 'intermediate', E'Drive through the top leg, minimal push from the floor leg\nHold balance at the top briefly\nStep down with control', '{single_leg_unstable}', true),
('Step-Up to Balance with Curl and Press', 'Step-up to balance adding a bicep curl and overhead press at the top.', 'lunge', 'Functional movement', '{quads,glutes,shoulders}', '{box,dumbbell}', 'advanced', E'Step up first, then curl and press\nHold balance throughout the upper-body work\nStep down with control', '{single_leg_unstable,overhead}', true),
('Squat to Row', 'Squat combined with a banded row at the top.', 'squat', 'Functional movement', '{quads,glutes,back}', '{band}', 'beginner', E'Squat down, stand and row together\nSqueeze the shoulder blades at the top\nControl the band back', '{deep_knee_flexion}', false),
('Squat to Curl to Press', 'Squat combined with a bicep curl and overhead press as you stand.', 'squat', 'Functional movement', '{quads,glutes,shoulders,biceps}', '{dumbbell}', 'intermediate', E'Squat down, curl and press as you stand\nFull lockout overhead at the top\nLight weight — three movements in one rep adds up', '{deep_knee_flexion,overhead}', false),
('Lunge to Curl to Press', 'Lunge combined with a bicep curl and overhead press.', 'lunge', 'Functional movement', '{quads,glutes,shoulders,biceps}', '{dumbbell}', 'intermediate', E'Lunge down, curl and press as you return to standing\nKeep the front knee stable\nLight weight to start', '{deep_knee_flexion,overhead}', true),
('Single-Leg Scaption', 'Single-leg balance combined with a shoulder raise in the scapular plane.', 'push_vertical', 'Functional movement', '{shoulders,core}', '{dumbbell}', 'advanced', E'Balance first, raise the arms at about a 30-degree angle forward\nLight weight — this is a stability challenge, not a strength one\nReset if balance breaks down', '{single_leg_unstable}', true),

-- MORE CABLE WORK ────────────────────────────────────────────────────
('Standing Cable Chest Press', 'Standing single- or split-stance cable press.', 'push_horizontal', 'Foundational strength', '{chest,triceps,core}', '{cable_machine}', 'beginner', E'Split stance for stability\nPress straight ahead, resist rotating\nControl the return', '{}', false),
('Single-Arm Cable Chest Press', 'Standing cable press performed one arm at a time.', 'push_horizontal', 'Foundational strength', '{chest,triceps,core}', '{cable_machine}', 'intermediate', E'Split stance, brace against rotation\nPress straight ahead\nControl the return', '{}', true),
('Standing Cable Row', 'Standing single- or double-handle cable row.', 'pull_horizontal', 'Foundational strength', '{back,biceps}', '{cable_machine}', 'beginner', E'Split stance, tall posture\nPull to the ribs, squeeze the shoulder blades\nControl the return', '{}', false),
('Single-Arm Cable Row', 'Standing cable row performed one arm at a time.', 'pull_horizontal', 'Foundational strength', '{back,biceps,core}', '{cable_machine}', 'intermediate', E'Resist rotating toward the working side\nPull to the hip\nControl the return', '{}', true),
('Bent-Over Barbell Row', 'Hinged barbell row targeting the mid-back.', 'pull_horizontal', 'Foundational strength', '{back,biceps}', '{barbell}', 'intermediate', E'Hold the hinge, flat back\nPull to the lower ribs\nControl the descent', '{heavy_spinal_load}', false),
('Machine Shoulder Press', 'Seated machine overhead press.', 'push_vertical', 'Foundational strength', '{shoulders,triceps}', '{full_gym}', 'beginner', E'Seat height so handles start at shoulder level\nFull lockout without shrugging\nControl the descent', '{overhead}', false),
('Dumbbell Scaption', 'Standing shoulder raise in the scapular plane (about 30 degrees forward of straight out to the side).', 'push_vertical', 'Foundational strength', '{shoulders}', '{dumbbell}', 'beginner', E'Thumbs slightly up, raise to shoulder height\nLight weight — this is a small, precise muscle group\nControl the descent', '{}', false),
('Ball Dumbbell Chest Press', 'Dumbbell chest press with the upper back supported on a stability ball.', 'push_horizontal', 'Foundational strength', '{chest,triceps,core}', '{stability_ball,dumbbell}', 'advanced', E'Hips up, shoulders and head supported on the ball\nBrace the core to stay stable\nControl the descent', '{}', false),
('Stability-Ball Push-Up', 'Push-up with the hands or feet on a stability ball.', 'push_horizontal', 'Foundational strength', '{chest,triceps,core}', '{stability_ball}', 'advanced', E'Extra core demand from the instability\nStart with feet on the ball, hands on the floor, if new to this\nControl the whole range', '{wrist_extension_load}', false),

-- MEDICINE BALL THROWS ───────────────────────────────────────────────
('Medicine-Ball Chest Pass', 'Explosive two-hand chest pass against a wall or to a partner.', 'push_horizontal', 'HIIT', '{chest,triceps}', '{medicine_ball}', 'intermediate', E'Load back, explode the ball forward\nCatch and immediately reload\nPace for quality reps', '{}', false),
('Medicine-Ball Pullover Throw', 'Overhead throw driving a medicine ball backward from an overhead position.', 'conditioning', 'HIIT', '{lats,core}', '{medicine_ball}', 'intermediate', E'Load overhead, then explosively throw backward\nFull hip and core involvement\nGood distance to throw into', '{overhead}', false),
('Medicine-Ball Soccer Throw', 'Explosive overhead throw driving a medicine ball forward.', 'conditioning', 'HIIT', '{core,shoulders}', '{medicine_ball}', 'intermediate', E'Load the ball overhead, drive forward through the hips\nFollow through with the whole body\nCatch and reset', '{}', false),
('Medicine-Ball Side Throw', 'Rotational side throw driving a medicine ball explosively away from the body.', 'core_antirotation', 'HIIT', '{core,obliques}', '{medicine_ball}', 'intermediate', E'Load by rotating away, then explode through\nFull hip rotation drives the throw\nAlternate sides', '{loaded_rotation}', true),
('Medicine-Ball Slam', 'Overhead slam driving a medicine ball into the floor with full-body force.', 'conditioning', 'HIIT', '{core,shoulders,lats}', '{medicine_ball}', 'intermediate', E'Full extension overhead, then slam down hard\nBend the knees to pick it back up, not the back\nGreat stress reliever, pace yourself', '{overhead,high_impact}', false),

-- JUMP / STABILIZATION SERIES ────────────────────────────────────────
('Squat Jump with Stabilization', 'Squat jump landing and holding a stable position rather than rebounding.', 'squat', 'HIIT', '{quads,glutes}', '{bodyweight}', 'advanced', E'Jump with intent, land soft and hold\nFull stick — no rebounding into the next jump\nReset fully between reps', '{high_impact,knee_dominant_plyo,deep_knee_flexion}', false),
('Box Jump-Up with Stabilization', 'Jump onto a box and hold the landing position.', 'conditioning', 'HIIT', '{quads,glutes}', '{box}', 'advanced', E'Full hip extension at the top\nStick the landing on the box, don''t rebound\nStep down between reps', '{high_impact,knee_dominant_plyo}', false),
('Box Jump-Down with Stabilization', 'Step off a box and stick the landing on the floor.', 'conditioning', 'HIIT', '{quads,glutes}', '{box}', 'advanced', E'Step off, don''t jump up first\nLand soft with bent knees, hold it\nUse a modest box height to start', '{high_impact}', false),
('Multiplanar Jump with Stabilization', 'Jumping in varying directions (forward, lateral, rotational) sticking each landing.', 'conditioning', 'HIIT', '{quads,glutes,core}', '{bodyweight}', 'advanced', E'Change jump direction each rep\nFull stick on every landing before the next jump\nQuality over speed', '{high_impact,knee_dominant_plyo,cutting}', false),

-- AGILITY / CONDITIONING DRILLS ──────────────────────────────────────
('Power Step-Up', 'Explosive step-up driving off the top leg into a small hop.', 'lunge', 'HIIT', '{quads,glutes}', '{box}', 'advanced', E'Drive hard through the top leg\nLand soft, reset\nModerate box height for this one', '{high_impact,knee_dominant_plyo}', true),
('Butt Kicks', 'Light jogging drill kicking the heels up toward the glutes.', 'conditioning', 'HIIT', '{hamstrings,calves}', '{bodyweight}', 'beginner', E'Quick, light steps\nHeels kick up and back, not just down\nStay tall through the torso', '{high_impact}', false),
('In-In-Out-Out Ladder Drill', 'Agility ladder footwork drill stepping in-in-out-out through each rung.', 'conditioning', 'HIIT', '{calves,quads}', '{bodyweight}', 'intermediate', E'Quick, light feet\nStart slow to nail the pattern before speeding up\nStay low and athletic', '{high_impact,cutting}', false),
('Side Shuffle', 'Lateral shuffling movement staying low and athletic.', 'conditioning', 'HIIT', '{glutes,adductors}', '{bodyweight}', 'intermediate', E'Stay low, don''t let the feet click together\nQuick, controlled steps\nKeep the chest up', '{cutting}', false),
('Cone Shuffles', 'Lateral shuffling between two cones, touching the ground at each.', 'conditioning', 'HIIT', '{glutes,adductors,quads}', '{bodyweight}', 'intermediate', E'Stay low throughout\nTouch the ground under control, don''t overreach\nQuick change of direction', '{cutting,high_impact}', false),
('Pro Shuttle', 'Sprint shuttle drill covering set distances with direction changes (5-10-5 pattern).', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'advanced', E'Low, powerful first step out of each turn\nTouch the line with a hand where required\nFull effort, full recovery between reps', '{cutting,high_impact}', false),
('T-Drill', 'Agility drill sprinting, shuffling, and backpedaling in a T-shaped pattern.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'advanced', E'Sprint the straightaways, shuffle the sides, stay low\nDon''t cross the feet on the shuffle\nBackpedal under control on the return', '{cutting,high_impact}', false);
