-- NASM PES-sourced batch, deduplicated against the real 400-exercise
-- library (checked against actual DB names, not just eyeballing) AND
-- against extensive repetition within the source list itself. Many NASM
-- families are 5-40 near-identical variants of the same underlying drill
-- (five near-identical "wall drill" sprint-mechanics variants, 40+
-- near-identical agility-ladder footwork patterns, 20+ near-identical
-- reaction-drill stimulus variants, dozens of "Heavy ___" entries that
-- are intensity notes on exercises already in the library, not new
-- movements). Those were consolidated to a small number of genuinely
-- representative entries rather than exhaustively itemized — bloating
-- the library with near-duplicates of each other serves nobody. Written
-- originally, same tagging vocabulary and category set as every prior
-- batch — no new contraindication tags, equipment types, or categories.

insert into exercises
  (name, description, pattern, category, muscle_groups, equipment_types, difficulty, cues, contraindication_tags, unilateral)
values

-- DYNAMIC WARM-UP ────────────────────────────────────────────────────
('Arm Circles', 'Standing dynamic shoulder warm-up circling the arms.', 'mobility', 'Foundational strength', '{shoulders}', '{bodyweight}', 'beginner', E'Small circles first, build to bigger ones\nBoth directions\nGreat first mover of a warm-up', '{}', false),
('Arm Swings', 'Standing dynamic drill swinging the arms across the body and back.', 'mobility', 'Foundational strength', '{shoulders,chest}', '{bodyweight}', 'beginner', E'Let the swing build gradually\nCross the arms, then open wide\nControlled, not violent', '{}', false),
('Walking Knee Hug', 'Walking drill pulling one knee to the chest each step.', 'mobility', 'Foundational strength', '{glutes,hip_flexors}', '{bodyweight}', 'beginner', E'Pull the knee up and in, brief pause\nStay tall through the step\nAlternate legs', '{single_leg_unstable}', true),
('Walking Knee Hug to Lunge', 'Walking knee hug immediately followed by a forward lunge step.', 'lunge', 'Foundational strength', '{glutes,quads,hip_flexors}', '{bodyweight}', 'intermediate', E'Hug the knee, then step into the lunge\nFront knee tracks over the toes\nAlternate legs', '{deep_knee_flexion,single_leg_unstable}', true),
('Walking Quad Stretch', 'Walking drill pulling one heel toward the glutes each step.', 'mobility', 'Foundational strength', '{quads}', '{bodyweight}', 'beginner', E'Brief pull, don''t overstretch mid-stride\nStay tall\nAlternate legs', '{single_leg_unstable}', true),
('Walking Hamstring Stretch', 'Walking drill with an alternating straight-leg toe touch.', 'mobility', 'Foundational strength', '{hamstrings}', '{bodyweight}', 'beginner', E'Reach toward the toes with a flat back\nDon''t force the range\nAlternate legs', '{}', true),
('Walking Spiderman', 'Walking lunge with the same-side hand reaching to the floor beside the front foot.', 'lunge', 'Foundational strength', '{hip_flexors,adductors,chest}', '{bodyweight}', 'intermediate', E'Deep lunge, hand or elbow to the floor\nOpen the chest toward the front knee\nAlternate legs', '{deep_knee_flexion}', true),
('Spiderman with Rotation', 'Walking Spiderman lunge adding a trunk rotation and overhead reach.', 'lunge', 'Foundational strength', '{hip_flexors,obliques,shoulders}', '{bodyweight}', 'advanced', E'Lunge deep, then rotate and reach up\nOpen through the whole trunk\nAlternate legs', '{deep_knee_flexion,loaded_rotation}', true),
('Reverse Lunge with Reach', 'Reverse lunge adding a forward overhead reach.', 'lunge', 'Foundational strength', '{quads,glutes,shoulders}', '{bodyweight}', 'intermediate', E'Step back, reach forward and up together\nKeep the front knee stable\nAlternate legs', '{deep_knee_flexion,overhead}', true),
('Drop Lunge', 'Lateral-to-behind stepping lunge crossing one leg behind the other.', 'lunge', 'Foundational strength', '{glutes,adductors}', '{bodyweight}', 'intermediate', E'Cross the leg behind and drop into the lunge\nKeep the front foot flat\nAlternate legs', '{deep_knee_flexion}', true),
('A-March', 'Marching drill driving the knee up to hip height with a strike-down.', 'conditioning', 'HIIT', '{hip_flexors,glutes}', '{bodyweight}', 'beginner', E'Drive the knee to hip height\nStrike the ground under the hip, not out front\nTall posture throughout', '{}', false),
('A-Skip', 'Skipping drill combining the A-March pattern with a hop.', 'conditioning', 'HIIT', '{hip_flexors,glutes,calves}', '{bodyweight}', 'intermediate', E'Same knee drive as the A-March, add a small hop\nUse the arms for rhythm\nStay tall', '{high_impact}', false),
('B-Skip', 'Skipping drill adding a leg extension and pull-down after the knee drive.', 'conditioning', 'HIIT', '{hamstrings,hip_flexors,calves}', '{bodyweight}', 'advanced', E'Drive the knee, extend the leg, then pull down and back\nMore advanced than an A-skip\nStay tall', '{high_impact}', false),
('Straight-Leg March', 'Marching drill kicking a straight leg forward to hip height.', 'conditioning', 'HIIT', '{hamstrings,hip_flexors}', '{bodyweight}', 'beginner', E'Leg stays straight, kick to about hip height\nOpposite arm drives forward\nStay tall', '{}', false),
('Straight-Leg Run', 'Running drill with straight-leg kicks, faster tempo than the march.', 'conditioning', 'HIIT', '{hamstrings,hip_flexors}', '{bodyweight}', 'intermediate', E'Same pattern as the march, quicker tempo\nStay tall, quick ground contact\nGood hamstring activation drill', '{high_impact}', false),
('Backward Run', 'Running backward under control at moderate speed.', 'conditioning', 'HIIT', '{quads,glutes}', '{bodyweight}', 'intermediate', E'Stay low, quick steps, look over the shoulder periodically\nDon''t overstride\nOpen space needed', '{}', false),
('Pogo Jumps', 'Rapid, small, stiff-ankled hops in place.', 'conditioning', 'HIIT', '{calves}', '{bodyweight}', 'intermediate', E'Minimal knee bend — this is an ankle-driven hop\nQuick ground contact\nStay light and springy', '{high_impact}', false),
('Ankle Hops', 'Small rapid hops emphasizing quick ground contact through the ankles.', 'conditioning', 'HIIT', '{calves}', '{bodyweight}', 'beginner', E'Small hops, quick and light\nMinimize time on the ground\nGreat plyometric warm-up', '{high_impact}', false),
('Leg Swings — Front to Back', 'Standing dynamic drill swinging one leg forward and backward.', 'mobility', 'Foundational strength', '{hip_flexors,hamstrings}', '{bodyweight}', 'beginner', E'Hold something for balance if needed\nLet the swing build gradually\nAlternate legs', '{single_leg_unstable}', true),
('Leg Swings — Side to Side', 'Standing dynamic drill swinging one leg across the body and back out.', 'mobility', 'Foundational strength', '{adductors,glutes}', '{bodyweight}', 'beginner', E'Hold something for balance if needed\nControlled swing, don''t force the range\nAlternate legs', '{single_leg_unstable}', true),
('Hip Openers', 'Standing dynamic drill lifting the knee up and rotating the hip open.', 'mobility', 'Foundational strength', '{hips,glutes}', '{bodyweight}', 'beginner', E'Knee up, then rotate the hip open\nControlled, not ballistic\nAlternate legs', '{single_leg_unstable}', true),
('Hip Closers', 'Standing dynamic drill rotating the hip across the body toward center.', 'mobility', 'Foundational strength', '{hips,adductors}', '{bodyweight}', 'beginner', E'Knee up, rotate the hip across and in\nControlled, not ballistic\nAlternate legs', '{single_leg_unstable}', true),
('Lateral Bear Crawl', 'Bear crawl moving sideways instead of forward.', 'core_antiextension', 'Functional movement', '{core,shoulders}', '{bodyweight}', 'intermediate', E'Hips low, knees hover just off the floor\nMove hand and foot together on the same side\nStay low throughout', '{wrist_extension_load}', false),
('Crab Walk', 'Walking on hands and feet with the body facing upward.', 'core_antiextension', 'Functional movement', '{triceps,glutes,core}', '{bodyweight}', 'intermediate', E'Hips lifted, don''t let them sag\nMove hand and foot together on the same side\nShort, controlled steps', '{wrist_extension_load}', false),

-- SELF-MYOFASCIAL RELEASE ────────────────────────────────────────────
('Foam Roll — Peroneals', 'Self-myofascial release for the outer lower leg.', 'mobility', 'Foundational strength', '{calves}', '{foam_roller}', 'beginner', E'Roller along the outside of the lower leg\nSlow passes, pause on tender spots\nLight pressure to start', '{}', true),
('Foam Roll — Hamstrings', 'Self-myofascial release for the back of the thigh.', 'mobility', 'Foundational strength', '{hamstrings}', '{foam_roller}', 'beginner', E'Seated, roller under the thigh\nSlow passes from knee to glute\nPause on tender spots', '{}', false),
('Foam Roll — Tensor Fasciae Latae', 'Self-myofascial release for the front-outer hip.', 'mobility', 'Foundational strength', '{hips}', '{foam_roller}', 'beginner', E'Roller angled at the front-outer hip\nSlow passes, pause on tender spots\nLight pressure to start', '{}', true),
('Foam Roll — Quadriceps', 'Self-myofascial release for the front of the thigh.', 'mobility', 'Foundational strength', '{quads}', '{foam_roller}', 'beginner', E'Prone, roller under the thighs\nSlow passes from hip to knee\nPause on tender spots', '{prone}', false),
('Foam Roll — Gluteals', 'Self-myofascial release for the glutes.', 'mobility', 'Foundational strength', '{glutes}', '{foam_roller}', 'beginner', E'Seated on the roller, cross one ankle over the opposite knee\nSlow passes, pause on tender spots\nSwitch sides', '{}', true),
('Foam Roll — Piriformis', 'Self-myofascial release for the deep glute/piriformis.', 'mobility', 'Foundational strength', '{glutes}', '{foam_roller}', 'beginner', E'Cross one ankle over the opposite knee, lean into that side\nSlow passes, pause on tender spots\nSwitch sides', '{}', true),
('Foam Roll — Thoracic Spine', 'Self-myofascial release for the mid/upper back.', 'mobility', 'Foundational strength', '{back}', '{foam_roller}', 'beginner', E'Roller across the upper back, support the head with the hands\nSmall controlled passes\nAvoid rolling directly on the low back', '{}', false),
('Foam Roll — Pectorals', 'Self-myofascial release for the chest, lying face down.', 'mobility', 'Foundational strength', '{chest}', '{foam_roller}', 'beginner', E'Prone, roller angled under one side of the chest\nSlow passes, pause on tender spots\nSwitch sides', '{prone}', true),
('Foam Roll — Biceps', 'Self-myofascial release for the front of the upper arm.', 'mobility', 'Foundational strength', '{biceps}', '{foam_roller}', 'beginner', E'Forearm supported, roller under the bicep\nSlow passes, light pressure\nSwitch sides', '{}', true),
('Foam Roll — Triceps', 'Self-myofascial release for the back of the upper arm.', 'mobility', 'Foundational strength', '{triceps}', '{foam_roller}', 'beginner', E'Roller under the back of the upper arm\nSlow passes, light pressure\nSwitch sides', '{}', true),
('Foam Roll — Plantar Fascia', 'Self-myofascial release for the bottom of the foot, typically using a ball.', 'mobility', 'Foundational strength', '{calves}', '{foam_roller}', 'beginner', E'Stand and roll a ball or roller under the arch\nModerate pressure, slow passes\nSwitch feet', '{}', true),

-- FLEXIBILITY ────────────────────────────────────────────────────────
('Soleus Stretch', 'Bent-knee calf stretch isolating the soleus, distinct from the straight-leg gastrocnemius stretch.', 'mobility', 'Foundational strength', '{calves}', '{bodyweight}', 'beginner', E'Bend the back knee this time, unlike the standard calf stretch\nBack heel stays down\nHold and breathe', '{}', true),
('Latissimus Dorsi Stretch', 'Standing or kneeling lat stretch without a ball.', 'mobility', 'Foundational strength', '{back}', '{bodyweight}', 'beginner', E'Reach overhead and lean to the side\nFeel the stretch down the side of the back\nHold, switch sides', '{}', true),
('Posterior Shoulder Stretch', 'Cross-body arm stretch targeting the back of the shoulder.', 'mobility', 'Foundational strength', '{shoulders}', '{bodyweight}', 'beginner', E'Pull the arm across the body gently\nKeep the shoulder down, not shrugged\nHold, switch sides', '{}', true),
('Upper-Trapezius Stretch', 'Seated or standing stretch tilting the head to release the upper traps.', 'mobility', 'Foundational strength', '{neck}', '{bodyweight}', 'beginner', E'Very gentle — small sensitive area\nEar toward the shoulder, light hand assist only\nHold, switch sides', '{}', true),
('Active Calf Stretch', 'Dynamic ankle dorsiflexion drill against a wall or step.', 'mobility', 'Foundational strength', '{calves}', '{bodyweight}', 'beginner', E'Drive the knee toward the wall, heel stays down\nControlled reps, not a static hold\nSwitch legs', '{}', true),
('Active Hamstring Stretch', 'Dynamic straight-leg raise stretching the hamstring through active range.', 'mobility', 'Foundational strength', '{hamstrings}', '{bodyweight}', 'beginner', E'Lying down, raise a straight leg with control\nActively hold at the top briefly, then lower\nSwitch legs', '{supine_extended}', true),
('Active Hip-Flexor Stretch', 'Dynamic half-kneeling hip flexor stretch with a controlled pulse.', 'mobility', 'Foundational strength', '{hip_flexors}', '{bodyweight}', 'beginner', E'Half-kneeling, gently pulse forward and back\nTuck the tailbone under\nSwitch legs', '{}', true),
('Active Adductor Stretch', 'Dynamic side-to-side lunge stretching the inner thigh through motion.', 'mobility', 'Foundational strength', '{adductors}', '{bodyweight}', 'beginner', E'Shift side to side with control\nKeep the straight leg''s foot flat\nContinuous, controlled motion', '{}', false),
('Active Latissimus Dorsi Stretch', 'Dynamic overhead reach-and-release stretch for the lats.', 'mobility', 'Foundational strength', '{back}', '{bodyweight}', 'beginner', E'Reach up and over with control, then release\nRepeat with a controlled rhythm\nSwitch sides', '{overhead}', true),

-- CORE STABILIZATION ─────────────────────────────────────────────────
('Drawing-In Maneuver', 'Foundational core activation drawing the navel toward the spine.', 'core_antiextension', 'Foundational strength', '{core}', '{bodyweight}', 'beginner', E'Gently draw the belly button in and up\nDon''t hold your breath\nThis is a subtle activation, not a big movement', '{}', false),
('Abdominal Bracing', 'Foundational core activation bracing the entire trunk like absorbing a punch.', 'core_antiextension', 'Foundational strength', '{core}', '{bodyweight}', 'beginner', E'Brace all the way around, not just the front\nBreathe normally while braced\nGreat teaching cue before loaded lifts', '{}', false),
('Prone Iso-Ab', 'Isometric hold in a modified prone plank position with knees down.', 'core_antiextension', 'Foundational strength', '{core}', '{bodyweight}', 'beginner', E'Forearms and knees down, hips level\nHold steady, breathe\nGood regression before a full plank', '{}', false),
('Plank with Leg Lift', 'Forearm plank alternating a small straight-leg lift.', 'core_antiextension', 'Foundational strength', '{core,glutes}', '{bodyweight}', 'intermediate', E'Hips stay level, don''t rotate\nSmall controlled lift\nAlternate legs', '{}', true),
('Plank with Arm Lift', 'Forearm plank alternating a small arm lift forward.', 'core_antiextension', 'Foundational strength', '{core,shoulders}', '{bodyweight}', 'intermediate', E'Hips stay level, resist rotating\nSmall controlled lift\nAlternate arms', '{}', true),
('Plank with Alternating Arm and Leg Lift', 'Forearm plank lifting opposite arm and leg together.', 'core_antiextension', 'Foundational strength', '{core,glutes,shoulders}', '{bodyweight}', 'advanced', E'Hips stay level and square\nSmall controlled lift, opposite arm and leg\nAlternate sides', '{}', true),
('Side Plank with Hip Abduction', 'Side plank adding a small lift of the top leg.', 'core_antirotation', 'Foundational strength', '{core,obliques,glutes}', '{bodyweight}', 'advanced', E'Hold the plank, lift the top leg with control\nDon''t let the hips drop\nSwitch sides', '{}', true),
('Quadruped Leg Raise', 'On all fours, extending one leg straight back.', 'core_antirotation', 'Foundational strength', '{glutes,core}', '{bodyweight}', 'beginner', E'Hips and shoulders stay square\nExtend long, don''t just lift high\nAlternate legs', '{}', true),
('Half-Kneeling Pallof Press', 'Anti-rotation cable/band press performed from a half-kneeling position.', 'core_antirotation', 'Foundational strength', '{core,obliques}', '{band}', 'intermediate', E'Resist the pull, don''t let the trunk twist\nPress straight out and back\nSwitch sides', '{}', true),
('Tall-Kneeling Pallof Press', 'Anti-rotation cable/band press performed from a tall-kneeling position.', 'core_antirotation', 'Foundational strength', '{core,obliques}', '{band}', 'intermediate', E'Resist the pull, don''t let the trunk twist\nPress straight out and back\nSwitch sides', '{}', true),
('Stability-Ball Cobra', 'Prone back-extension activation performed over a stability ball.', 'pull_horizontal', 'Foundational strength', '{back,shoulders}', '{stability_ball}', 'beginner', E'Hips draped over the ball\nLift chest and arms with control, thumbs up\nDon''t hyperextend the low back', '{prone}', false),

-- CORE STRENGTH ──────────────────────────────────────────────────────
('Crunch with Rotation', 'Crunch adding a twist toward one knee.', 'core_flexion', 'Foundational strength', '{core,obliques}', '{bodyweight}', 'beginner', E'Curl and rotate together\nControl the lowering\nAlternate sides', '{loaded_flexion,supine_extended,loaded_rotation}', true),
('Stability-Ball Russian Twist', 'Russian twist performed with the upper back on a stability ball.', 'core_antirotation', 'Foundational strength', '{core,obliques}', '{stability_ball}', 'advanced', E'Hips up, shoulders and head on the ball\nRotate with control, don''t let the hips drop\nLight weight to start', '{loaded_rotation}', false),
('Kneeling Cable Chop', 'Tall-kneeling diagonal cable chop from high to low.', 'core_antirotation', 'Functional movement', '{core,obliques}', '{cable_machine}', 'intermediate', E'Kneeling stays tall and stable\nRotate and chop from the trunk\nSwitch sides', '{loaded_rotation}', true),

-- CORE POWER ─────────────────────────────────────────────────────────
('Medicine-Ball Scoop Toss', 'Underhand explosive toss scooping a medicine ball from low to high.', 'conditioning', 'HIIT', '{core,glutes,shoulders}', '{medicine_ball}', 'intermediate', E'Bend the knees to scoop low, extend to release high\nFull hip extension drives the throw\nCatch and reset', '{overhead}', false),
('Medicine-Ball Shot-Put Throw', 'Explosive one-arm push throw mimicking a shot put.', 'push_horizontal', 'HIIT', '{chest,shoulders,core}', '{medicine_ball}', 'intermediate', E'Load at the shoulder, drive through the hip and trunk\nFull extension at release\nAlternate sides', '{}', true),
('Medicine-Ball Sit-Up and Throw', 'Sit-up finishing with an explosive overhead throw at the top.', 'core_flexion', 'HIIT', '{core,shoulders}', '{medicine_ball}', 'intermediate', E'Sit up, then throw explosively at the top\nPartner or wall needed to catch/return\nControl the lowering', '{loaded_flexion,supine_extended,overhead}', false),

-- BALANCE STABILIZATION ──────────────────────────────────────────────
('Single-Leg Balance on Foam Pad', 'Single-leg balance hold performed on an unstable foam surface.', 'mobility', 'Functional movement', '{core,glutes}', '{bodyweight}', 'intermediate', E'More instability than standing on the floor\nStay light on the standing foot\nUse a wall for light support if needed', '{single_leg_unstable}', true),
('Single-Leg Balance Reach — Sagittal Plane', 'Single-leg balance reaching the free leg forward and back.', 'mobility', 'Functional movement', '{glutes,core}', '{bodyweight}', 'intermediate', E'Reach forward, then back, with control\nStay light on the standing foot\nSwitch legs', '{single_leg_unstable}', true),
('Single-Leg Balance Reach — Transverse Plane', 'Single-leg balance reaching the free leg across the body in a rotational plane.', 'mobility', 'Functional movement', '{glutes,core,obliques}', '{bodyweight}', 'advanced', E'Reach across the body with control\nStay light on the standing foot\nSwitch legs', '{single_leg_unstable,loaded_rotation}', true),
('Single-Leg Hip Internal and External Rotation', 'Single-leg balance rotating the standing hip in and out.', 'mobility', 'Functional movement', '{hips,glutes}', '{bodyweight}', 'advanced', E'Small controlled rotation of the standing hip\nStay light and balanced\nSwitch legs', '{single_leg_unstable}', true),
('Single-Leg Balance with Cable Row', 'Single-leg balance combined with a cable row.', 'pull_horizontal', 'Functional movement', '{back,core,glutes}', '{cable_machine}', 'advanced', E'Balance first, then row with control\nKeep the hips square\nSwitch legs', '{single_leg_unstable}', true),
('Single-Leg Balance with Cable Press', 'Single-leg balance combined with a cable chest press.', 'push_horizontal', 'Functional movement', '{chest,core,glutes}', '{cable_machine}', 'advanced', E'Balance first, then press with control\nResist rotating as you press\nSwitch legs', '{single_leg_unstable}', true),

-- BALANCE STRENGTH ───────────────────────────────────────────────────
('Single-Leg Romanian Deadlift with PNF Pattern', 'Single-leg RDL adding a diagonal reach pattern as you hinge.', 'hinge', 'Functional movement', '{hamstrings,glutes,core}', '{dumbbell}', 'advanced', E'Hinge and reach diagonally across the body\nHips stay square\nSwitch legs', '{single_leg_unstable}', true),
('Reverse Lunge to Balance', 'Reverse lunge returning to a single-leg balance hold instead of full stance.', 'lunge', 'Functional movement', '{quads,glutes,core}', '{bodyweight}', 'intermediate', E'Step back, drive forward into balance, not all the way to standing\nHold briefly before the next rep\nSwitch legs', '{single_leg_unstable,deep_knee_flexion}', true),
('Lateral Lunge to Balance', 'Lateral lunge returning to a single-leg balance hold.', 'lunge', 'Functional movement', '{glutes,adductors,core}', '{bodyweight}', 'intermediate', E'Push hips back into the lunge, drive back to balance\nHold briefly before the next rep\nSwitch legs', '{single_leg_unstable,deep_knee_flexion}', true),
('Transverse Lunge to Balance', 'Rotational lunge stepping at an angle, returning to a single-leg balance hold.', 'lunge', 'Functional movement', '{glutes,obliques,core}', '{bodyweight}', 'advanced', E'Step at a rotated angle, drive back to balance\nHold briefly before the next rep\nSwitch legs', '{single_leg_unstable,deep_knee_flexion,loaded_rotation}', true),
('Lateral Step-Up to Balance', 'Step-up performed sideways onto a box, finishing in single-leg balance.', 'lunge', 'Functional movement', '{quads,glutes,core}', '{box}', 'intermediate', E'Drive up through the working leg\nHold balance briefly at the top\nStep down with control', '{single_leg_unstable}', true),
('Step-Down to Balance', 'Controlled step down from a box finishing in single-leg balance.', 'squat', 'Functional movement', '{quads,glutes,core}', '{box}', 'intermediate', E'Lower with control, don''t drop\nHold balance at the bottom\nSwitch legs', '{single_leg_unstable,deep_knee_flexion}', true),
('Single-Leg Squat to Cable Press', 'Single-leg squat combined with a cable chest press at the bottom.', 'squat', 'Functional movement', '{quads,glutes,chest,core}', '{cable_machine}', 'advanced', E'Squat first, press at the bottom\nKeep the working knee stable\nSwitch legs', '{single_leg_unstable,deep_knee_flexion}', true),

-- BALANCE POWER ──────────────────────────────────────────────────────
('Single-Leg Hop with Stabilization', 'Single-leg hop in place, sticking the landing each time.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'advanced', E'Land soft, hold before the next hop\nSmall hop height to start\nSwitch legs', '{high_impact,single_leg_unstable}', true),
('Single-Leg Rotational Hop with Stabilization', 'Single-leg hop rotating in the air, sticking the landing.', 'conditioning', 'HIIT', '{quads,glutes,core}', '{bodyweight}', 'advanced', E'Small rotation to start, land soft and hold\nBuild up the rotation gradually\nSwitch legs', '{high_impact,single_leg_unstable,cutting}', true),
('Single-Leg Box Hop-Up with Stabilization', 'Single-leg hop onto a box, sticking the landing.', 'conditioning', 'HIIT', '{quads,glutes}', '{box}', 'advanced', E'Full hip extension at the top\nStick the landing on the box\nModerate box height to start', '{high_impact,single_leg_unstable,knee_dominant_plyo}', true),
('Single-Leg Box Hop-Down with Stabilization', 'Single-leg step-off from a box, sticking the landing on the floor.', 'conditioning', 'HIIT', '{quads,glutes}', '{box}', 'advanced', E'Step off, don''t jump up first\nLand soft with a bent knee, hold it\nModerate box height to start', '{high_impact,single_leg_unstable}', true),

-- PLYOMETRIC STABILIZATION ───────────────────────────────────────────
('Cone Hop with Stabilization', 'Two-foot hop over a low cone, sticking the landing before the next hop.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'intermediate', E'Hop over, land soft and hold\nReset fully between hops\nSmall cone height to start', '{high_impact}', false),
('Depth Landing', 'Stepping off a low box and sticking the landing, no rebound.', 'conditioning', 'HIIT', '{quads,glutes}', '{box}', 'intermediate', E'Step off, don''t jump\nLand soft with bent knees, hold it\nLow box height — this teaches landing mechanics', '{high_impact}', false),
('Snap-Down', 'Quick drop from standing into a low, stable athletic position.', 'squat', 'HIIT', '{quads,glutes,core}', '{bodyweight}', 'intermediate', E'Drop quickly, stick the low position\nChest up, weight in the mid-foot\nGreat landing-mechanics teaching drill', '{deep_knee_flexion}', false),
('Drop Squat with Stabilization', 'Small hop into a squat position, holding the bottom.', 'squat', 'HIIT', '{quads,glutes}', '{bodyweight}', 'intermediate', E'Small hop, land directly into a held squat\nChest up, knees track over the toes\nHold briefly before resetting', '{deep_knee_flexion,high_impact}', false),

-- PLYOMETRIC STRENGTH ────────────────────────────────────────────────
('Split-Squat Jump', 'Explosive jump from a split stance, switching legs in the air.', 'lunge', 'HIIT', '{quads,glutes}', '{bodyweight}', 'advanced', E'Jump with intent, switch legs mid-air\nLand soft in the split stance\nReset pace if landings get sloppy', '{high_impact,knee_dominant_plyo,deep_knee_flexion}', false),
('Scissor Jump', 'Alternating split-stance jump switching the front leg each rep, similar to a split-squat jump with a quicker tempo.', 'lunge', 'HIIT', '{quads,glutes}', '{bodyweight}', 'advanced', E'Quick switch, land soft each time\nStay light on the feet\nReset pace if landings get sloppy', '{high_impact,knee_dominant_plyo}', false),
('Lateral Box Jump', 'Sideways two-foot jump onto a box.', 'conditioning', 'HIIT', '{quads,glutes,adductors}', '{box}', 'advanced', E'Full hip extension, land soft on the box\nModerate box height to start\nStep down between reps', '{high_impact,knee_dominant_plyo}', false),
('Depth Jump', 'Stepping off a box and immediately jumping upon landing.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{box}', 'advanced', E'Step off, land, and immediately explode up\nMinimal ground contact time\nAdvanced — build up from depth landings first', '{high_impact,knee_dominant_plyo}', false),
('Broad Jump', 'Two-foot standing jump for maximum forward distance.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'advanced', E'Load with an arm swing, jump for distance\nLand soft with bent knees\nOpen space needed', '{high_impact,knee_dominant_plyo}', false),
('Lateral Bound', 'Sideways single-leg bound landing and sticking on the opposite leg.', 'conditioning', 'HIIT', '{glutes,adductors,quads}', '{bodyweight}', 'advanced', E'Push off one leg, land soft on the other and stick\nBuild distance gradually\nAlternate directions', '{high_impact,single_leg_unstable,cutting}', true),
('Double-Leg Bound', 'Repeated forward two-foot bounds covering distance.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'advanced', E'Bound continuously, minimal pause between\nUse the arms for drive\nOpen space needed', '{high_impact,knee_dominant_plyo}', false),

-- UPPER-BODY PLYOMETRICS ─────────────────────────────────────────────
('Clap Push-Up', 'Explosive push-up with a clap at the top of the push.', 'push_horizontal', 'HIIT', '{chest,triceps,shoulders}', '{bodyweight}', 'advanced', E'Push explosively, clap, land soft with bent elbows\nKeep the plank line tight\nAdvanced — build up from plyometric push-ups first', '{wrist_extension_load,high_impact}', false),
('Depth Push-Up', 'Push-up starting with the hands elevated, dropping to the floor and pushing back up.', 'push_horizontal', 'HIIT', '{chest,triceps,shoulders}', '{bodyweight,box}', 'advanced', E'Drop from the elevated position, absorb and push back explosively\nKeep the plank line tight\nAdvanced progression', '{wrist_extension_load,high_impact}', false),
('Jump Squat with Medicine-Ball Chest Pass', 'Squat jump immediately followed by an explosive medicine-ball chest pass.', 'squat', 'HIIT', '{quads,glutes,chest}', '{medicine_ball}', 'advanced', E'Jump first, land, then pass explosively\nFull hip extension on the jump\nCatch and reset', '{high_impact,knee_dominant_plyo,deep_knee_flexion}', false),

-- SPEED MECHANICS (consolidated — see migration header) ──────────────
('Wall Drill (Sprint Mechanics)', 'Leaning against a wall practicing driving knee/arm sprint mechanics in place.', 'conditioning', 'HIIT', '{hip_flexors,quads}', '{bodyweight}', 'intermediate', E'Lean into the wall, drive one knee at a time\nFocus on a strong, quick knee drive\nBuild tempo gradually', '{}', true),
('Arm-Action Drill', 'Seated or standing drill practicing sprint arm mechanics without the legs involved.', 'conditioning', 'HIIT', '{shoulders}', '{bodyweight}', 'beginner', E'Elbows at roughly 90 degrees\nDrive the arms front to back, not across the body\nBuild tempo gradually', '{}', false),
('Falling Start', 'Sprint start drill leaning forward from standing until forced to run.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'intermediate', E'Lean until you have to catch yourself with a step\nFirst steps should be short and quick\nOpen space needed', '{}', false),
('Three-Point Start', 'Sprint start from a three-point stance, common in field-sport contexts.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'intermediate', E'Low, athletic stance before the drive\nFirst few steps drive low and powerful\nOpen space needed', '{}', false),
('Acceleration Run', 'Short sprint focused on the first 10-20 yards of acceleration.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'intermediate', E'Drive low out of the start, gradually rise up\nPowerful arm drive\nFull recovery between reps', '{high_impact}', false),
('Build-Up Sprint', 'Sprint gradually increasing from jog to full speed over a set distance.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'intermediate', E'Start relaxed, build speed gradually\nRelax the face and shoulders even at speed\nFull recovery between reps', '{high_impact}', false),
('Tempo Run', 'Sub-maximal effort running at a controlled, moderately fast pace.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'intermediate', E'Roughly 70-80% effort, not a max sprint\nConsistent pace throughout\nGood for building a speed base', '{}', false),
('Flying Sprint', 'Sprint entering the timed/max-effort zone already at speed from a running start.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'advanced', E'Build to speed before the effort zone, then push\nFull recovery between reps\nAdvanced — needs a real speed base first', '{high_impact}', false),
('Resisted Sprint', 'Sprint against added resistance (band, sled, or partner-held).', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{sled,band}', 'advanced', E'Keep the same sprint mechanics despite the resistance\nDon''t let form break down\nFull recovery between reps', '{high_impact}', false),
('Hill Sprint', 'Sprinting up an incline for added resistance.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'advanced', E'Drive the knees, shorter steps than flat sprinting\nModerate grade to start\nFull recovery between reps', '{high_impact}', false),
('Sled Sprint', 'Sprinting while pushing or pulling a loaded sled.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{sled}', 'advanced', E'Drive through the legs, stay low on a push\nDon''t let the load break down your posture\nFull recovery between reps', '{high_impact}', false),

-- AGILITY (consolidated) ─────────────────────────────────────────────
('Crossover Run', 'Lateral running technique crossing one leg over the other while facing forward.', 'conditioning', 'HIIT', '{adductors,glutes}', '{bodyweight}', 'intermediate', E'Cross the trail leg over, hips stay athletic\nStay light and quick\nEqual reps each direction', '{cutting}', false),
('Forward-to-Backward Change of Direction', 'Sprinting forward then transitioning smoothly into a backpedal.', 'conditioning', 'HIIT', '{quads,glutes}', '{bodyweight}', 'advanced', E'Plant and flip the hips smoothly on the transition\nStay low through the change\nOpen space needed', '{cutting,high_impact}', false),
('Deceleration Drill', 'Sprinting then decelerating to a controlled stop over a short distance.', 'conditioning', 'HIIT', '{quads,glutes}', '{bodyweight}', 'intermediate', E'Widen the base and sink the hips to decelerate\nControl matters more than speed here\nFull recovery between reps', '{}', false),
('L-Drill', 'Agility drill sprinting and cutting in an L-shaped pattern around cones.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{box}', 'advanced', E'Sharp, low turns around each cone\nStay low and athletic throughout\nFull recovery between reps', '{cutting,high_impact}', false),
('Three-Cone Drill', 'Agility drill sprinting a triangular pattern between three cones.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{box}', 'advanced', E'Sharp turns, low center of gravity\nDrive out of every cut\nFull recovery between reps', '{cutting,high_impact}', false),
('Zigzag Drill', 'Agility drill cutting side to side through a line of cones.', 'conditioning', 'HIIT', '{quads,glutes,adductors}', '{box}', 'intermediate', E'Plant and cut sharply at each cone\nStay low throughout\nFull recovery between reps', '{cutting,high_impact}', false),
('Mirror Drill', 'Partner drill mirroring a leader''s lateral and multidirectional movements.', 'conditioning', 'HIIT', '{quads,glutes,adductors}', '{bodyweight}', 'intermediate', E'React to the partner, stay low and ready\nQuick, controlled steps\nSwitch roles', '{cutting}', false),
('Ball-Reaction Drill', 'Drill reacting to a dropped or thrown ball with a quick movement.', 'conditioning', 'HIIT', '{quads,glutes}', '{medicine_ball}', 'intermediate', E'Athletic ready position\nReact quickly once the ball moves\nGood for reaction time work', '{}', false),
('90-Degree Cut Drill', 'Running drill practicing a sharp 90-degree change of direction.', 'conditioning', 'HIIT', '{quads,glutes,adductors}', '{bodyweight}', 'advanced', E'Plant the outside foot, drive out of the cut\nStay low through the turn\nFull recovery between reps', '{cutting,high_impact}', false),

-- AGILITY LADDER (consolidated) ──────────────────────────────────────
('Ickey Shuffle', 'Classic agility ladder footwork pattern stepping in-in-out for each square.', 'conditioning', 'HIIT', '{calves,quads}', '{bodyweight}', 'intermediate', E'Quick, light feet\nStart slow to nail the pattern, then speed up\nStay low and athletic', '{high_impact}', false),
('Hopscotch (Ladder)', 'Agility ladder drill hopping in a hopscotch pattern through each square.', 'conditioning', 'HIIT', '{calves,quads}', '{bodyweight}', 'intermediate', E'Land soft each hop\nStart slow to nail the pattern\nStay light and quick', '{high_impact}', false),
('Lateral Ladder Shuffle', 'Agility ladder drill moving sideways through the ladder, one foot per square.', 'conditioning', 'HIIT', '{adductors,calves}', '{bodyweight}', 'beginner', E'Stay low, quick light feet\nDon''t cross the feet\nBoth directions through the ladder', '{high_impact}', false),

-- RESISTANCE STABILIZATION ───────────────────────────────────────────
('Ball Squat', 'Squat performed with a stability ball supporting the low back against a wall.', 'squat', 'Foundational strength', '{quads,glutes}', '{stability_ball}', 'beginner', E'Ball stays between the low back and the wall\nSquat down, ball rolls with you\nGreat regression for someone new to squatting', '{deep_knee_flexion}', false),
('Cable Squat', 'Squat performed holding a low cable for counterbalance.', 'squat', 'Foundational strength', '{quads,glutes}', '{cable_machine}', 'beginner', E'Cable provides counterbalance, not the primary load\nSit back into the squat\nDrive through the whole foot', '{deep_knee_flexion}', false),
('Single-Leg Dumbbell Curl', 'Bicep curl performed while balancing on one leg.', 'pull_horizontal', 'Functional movement', '{biceps,core}', '{dumbbell}', 'advanced', E'Balance first, curl with control\nLight weight — stability is the challenge here\nSwitch legs', '{single_leg_unstable}', true),
('Single-Leg Overhead Press', 'Overhead press performed while balancing on one leg.', 'push_vertical', 'Functional movement', '{shoulders,core}', '{dumbbell}', 'advanced', E'Balance first, press with control\nLight weight — stability is the challenge here\nSwitch legs', '{overhead,single_leg_unstable}', true),
('Stability-Ball Dumbbell Shoulder Press', 'Seated overhead press performed sitting on a stability ball.', 'push_vertical', 'Functional movement', '{shoulders,core}', '{stability_ball,dumbbell}', 'intermediate', E'Sit tall on the ball, brace the core\nPress to full lockout\nControl the descent', '{overhead}', false),

-- TRADITIONAL STRENGTH ───────────────────────────────────────────────
('Trap-Bar Deadlift', 'Deadlift performed inside a trap/hex bar, a more upright torso angle than a straight bar.', 'hinge', 'Foundational strength', '{glutes,hamstrings,quads}', '{full_gym}', 'intermediate', E'More upright torso than a straight-bar deadlift\nDrive through the floor, stand tall\nControl the descent', '{heavy_spinal_load}', false),
('Sumo Deadlift', 'Wide-stance deadlift with the hands inside the legs.', 'hinge', 'Foundational strength', '{glutes,adductors,hamstrings}', '{barbell}', 'intermediate', E'Wide stance, toes turned out\nChest up, drive the floor away\nStand tall to finish', '{heavy_spinal_load,deep_knee_flexion}', false),
('Nordic Hamstring Curl', 'Kneeling hamstring exercise lowering the torso forward under control with a partner or anchor holding the ankles.', 'hinge', 'Foundational strength', '{hamstrings}', '{bodyweight}', 'advanced', E'Ankles anchored, lower as slowly as you can control\nUse the hands to catch yourself at the bottom\nAdvanced — very demanding on the hamstrings', '{}', false),
('Glute-Ham Raise', 'Machine-assisted hamstring/glute exercise similar in pattern to a Nordic curl.', 'hinge', 'Foundational strength', '{hamstrings,glutes}', '{full_gym}', 'advanced', E'Control the lowering, don''t just drop\nUse the glutes and hamstrings together\nAdvanced movement', '{}', false),
('Weighted Push-Up', 'Push-up with added external load (plate or vest).', 'push_horizontal', 'Foundational strength', '{chest,triceps,shoulders}', '{bodyweight}', 'advanced', E'Same plank standards as a bodyweight push-up\nHave a spotter place the load\nFull range each rep', '{wrist_extension_load}', false),
('Barbell Overhead Press', 'Standing barbell press from the shoulders to full lockout overhead.', 'push_vertical', 'Foundational strength', '{shoulders,triceps}', '{barbell}', 'intermediate', E'Brace the core, press straight up\nFull lockout overhead\nControl the descent', '{overhead}', false),
('Upright Row', 'Standing pull bringing a barbell or dumbbells up along the body to chest height.', 'pull_vertical', 'Foundational strength', '{shoulders,traps}', '{barbell}', 'intermediate', E'Lead with the elbows\nStop around chest height\nControl the descent', '{}', false),

-- MAXIMAL STRENGTH / CARRIES ─────────────────────────────────────────
('Rack Carry', 'Loaded carry holding weights in the front-rack position.', 'carry', 'Foundational strength', '{core,shoulders,quads}', '{kettlebell}', 'intermediate', E'Elbows up, weights stay in the rack position\nTall posture throughout\nShort, controlled steps', '{front_rack}', false),
('Overhead Carry', 'Loaded carry holding weight locked out overhead.', 'carry', 'Foundational strength', '{shoulders,core}', '{kettlebell}', 'advanced', E'Full lockout overhead, stay tall\nBrace the core hard\nShort, controlled steps', '{overhead}', false),

-- OLYMPIC-STYLE LIFTS ────────────────────────────────────────────────
('Jump Shrug', 'Explosive barbell shrug with a small jump, a technique-building drill for the Olympic lifts.', 'hinge', 'Foundational strength', '{traps,glutes,hamstrings}', '{barbell}', 'advanced', E'Explosive hip extension, shrug at the top\nSmall jump, don''t pull with the arms\nAdvanced — a technique-building drill', '{}', false),
('Barbell High Pull', 'Explosive pull bringing a barbell up to chest height, elbows high.', 'hinge', 'Foundational strength', '{traps,shoulders,back}', '{barbell}', 'advanced', E'Drive with the hips first\nElbows lead and stay higher than the wrist\nControl the descent', '{}', false),
('Barbell Power Clean', 'Explosive full-body pull bringing a barbell from the floor to the shoulders.', 'hinge', 'Foundational strength', '{glutes,hamstrings,shoulders,traps}', '{barbell}', 'advanced', E'Hike back, then a violent hip extension\nCatch the bar at the shoulders, elbows up\nAdvanced technical lift — needs coaching', '{front_rack,heavy_spinal_load}', false),
('Clean and Jerk', 'Two-part Olympic lift: a power clean followed by a jerk overhead.', 'hinge', 'Foundational strength', '{glutes,shoulders,quads}', '{barbell}', 'advanced', E'Clean first, reset the rack, then drive it overhead\nFull lockout to finish\nAdvanced technical lift — needs coaching', '{front_rack,overhead,heavy_spinal_load}', false),
('Power Snatch', 'Explosive full-body pull bringing a barbell from the floor directly overhead in one motion.', 'hinge', 'Foundational strength', '{shoulders,glutes,hamstrings,traps}', '{barbell}', 'advanced', E'Wide grip, violent hip extension, catch overhead\nFull lockout at the top\nAdvanced technical lift — needs coaching', '{overhead,heavy_spinal_load}', false),
('Split Jerk', 'Explosive overhead drive from the shoulders, catching in a short front-back split stance.', 'push_vertical', 'Foundational strength', '{shoulders,quads,glutes}', '{barbell}', 'advanced', E'Dip and drive, split the feet as the bar goes overhead\nFull lockout to finish\nAdvanced technical lift — needs coaching', '{overhead}', false),

-- RESISTED / LOADED MOVEMENT ─────────────────────────────────────────
('Sled Drag', 'Pulling a loaded sled by rope or straps, walking backward or forward.', 'carry', 'Foundational strength', '{quads,glutes,back}', '{sled}', 'intermediate', E'Tall posture, drive through the legs\nSteady, controlled pace\nGreat low-impact conditioning tool', '{}', false),
('Front-Rack Carry', 'Loaded carry holding weight in the front-rack position at the shoulders, distinct from a standard rack carry using kettlebells specifically with a barbell or sandbag.', 'carry', 'Foundational strength', '{core,shoulders,quads}', '{sandbag}', 'intermediate', E'Elbows up, weight stays at the shoulders\nTall posture throughout\nShort, controlled steps', '{front_rack}', false),
('Bear-Hug Carry', 'Loaded carry hugging a sandbag or heavy object to the chest.', 'carry', 'Foundational strength', '{core,back,biceps}', '{sandbag}', 'intermediate', E'Hug the load tight to the chest\nTall posture, brace the core\nShort, controlled steps', '{}', false),

-- CONDITIONING ───────────────────────────────────────────────────────
('Battle-Rope Alternating Wave', 'Alternating single-arm waves with the ropes, the classic default battle-rope pattern.', 'conditioning', 'HIIT', '{shoulders,core}', '{battle_ropes}', 'beginner', E'Athletic stance, knees soft\nAlternate arms in a steady rhythm\nKeep breathing rhythmic', '{}', false),
('Air-Bike Sprint', 'Maximal-effort interval on an air/assault bike.', 'conditioning', 'HIIT', '{quads,shoulders,core}', '{stationary_bike}', 'intermediate', E'Full effort for the interval, both arms and legs\nSteady, controlled recovery pace between\nGreat low-impact max-effort tool', '{}', false),
('Fartlek Run', 'Unstructured run mixing random bursts of faster pace into a steady run.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'intermediate', E'Play with pace — pick up speed for a stretch, then ease off\nNo strict structure, just intuitive effort changes\nGreat for breaking up monotonous steady runs', '{}', false),
('Stair Sprint', 'Sprinting up a flight of stairs for conditioning.', 'conditioning', 'HIIT', '{quads,glutes,calves}', '{bodyweight}', 'intermediate', E'Drive the knees, use the rail if needed for safety\nControlled descent — most injuries happen going down\nFull recovery between reps', '{high_impact}', false),

-- SPORT-REACTION (consolidated) ──────────────────────────────────────
('Reaction-Based Sprint Drill', 'Sprint or agility movement triggered by an unpredictable visual, auditory, or verbal cue rather than a set count.', 'conditioning', 'HIIT', '{quads,glutes}', '{bodyweight}', 'advanced', E'Athletic ready position, react as fast as possible to the cue\nQuality over quantity — full recovery between reps\nGood for athletes needing real game-speed reaction work', '{cutting,high_impact}', false);
